### ISSUE TITLE
Replicate Soundflower/Loopback functionality to eliminate Facetime audio ducking

### ISSUE THREAD

**Issue by geraldlnj** [ExistentialAudio/BlackHole#109]
When a Facetime call starts, it lowers all other system sounds and it's quite annoying. I found this [link](https://apple.stackexchange.com/questions/189552/facetime-calls-lower-system-volume/314417#314417) that mentions using Loopback or Soundflower to eliminate it, and I want to know if i can replicate that with BlackHole. 

I want to be able to set the Facetime output device to BlackHole (this removes the audio ducking), then route the BlackHole output to my regular audio output. Any tips?

**Comment by devinroth** [comment]
BlakcHole works exactly like Soundflower.

**Comment by devinroth** [comment]
BlakcHole works exactly like Soundflower.

**Comment by fjarlq** [comment]
As far as I can tell, BlackHole alone cannot solve the Facetime audio ducking problem because [BlackHole is merely an audio driver, and as such does not (and will never) support outputting its audio to another audio device](https://github.com/ExistentialAudio/BlackHole/discussions/40#discussioncomment-5057672).

**Comment by devinroth** [comment]
Plenty of options out there for forwarding audio. But even then, how would it solve the problem?

Devin

**Comment by fjarlq** [comment]
> But even then, how would it solve the problem?

According to [this comment](https://apple.stackexchange.com/a/466306) and my own experimentation, macOS FaceTime only ducks the audio of other apps that are using the same audio output device as FaceTime.

That means you can disable the audio ducking by taking these steps which I learned from [another comment](https://apple.stackexchange.com/a/314417):

1. Install Rogue Amoeba's Loopback.
2. In Loopback, create a virtual audio device.
3. In Loopback, add a "[monitor](https://rogueamoeba.com/support/manuals/loopback/?page=monitors)" to the virtual audio device. Set the monitor to whatever audio output device you intend to use with FaceTime.
5. In FaceTime, set its audio output to the Loopback virtual device.
6. Now your other apps won't have their audio ducked during FaceTime calls because none of them are using the Loopback virtual device.

2026-02-10 edit: the below rumored fix was never actually released (I don't know why). Unwanted audio ducking is still happening ias of macOS 26.2:
Incidentally, I just learned that macOS 15 Sequoia [fixes FaceTime's audio ducking](https://www.reddit.com/r/MacOSBeta/comments/1dvq7zz/macos_15_db_2_finally_theyve_made_facetime_audio/):
> I am happy to report that [in macOS 15 DB 2] when you speak on FaceTime and you have audio playing you can listen to it at full volume if you so desire, and it will be ducked only when one of the participants speak.

**Comment by devinroth** [comment]
That’s pretty awesome they actually fixed it. So many people complain about that.

Devin
