### ISSUE TITLE
Distorted system audio with Bluetooth headset

### ISSUE THREAD

**Issue by Nithin-anim** [ExistentialAudio/BlackHole#181]
I created a multi-output device with my bluetooth headset and blackhole as per the docs.But when I am recording in QuickTime I hear a laggy, distorted system audio.But when I did the same with wired headset it works perfectly.Also, I made sure the builtin device (or in this case the bluetooth device ) is checked first in the Audio MIDI control.Is there any reason why BlackHole wouldn't support bluetooth headsets?

**Comment by devinroth** [comment]
BlackHole isn’t doing anything different for Bluetooth but maybe multi-output’s have issues with Bluetooth devices. 

Do you have drift correction enabled?

**Comment by Nithin-anim** [comment]
Yes I have drift correction enabled.
My particular use case is I want to record system audio along with my bluetooth headset mic.So I created a multi-output device with both bluetooth headset and BlackHole as sources and created an aggregate device with  bluetooth mic and  BlackHole as sources.That is when the distortion occurs in the system audio.

But when I change the default input to the macbook's mic it works perfectly.But ,now the problem is I can't record from my bluetooth mic.So,I want to record system audio along with my bluetooth mic.

**Comment by devinroth** [comment]
I am going to get some AirPods soon and will finally be able to look into this more.

**Comment by Lazare-42** [comment]
This is an issue I've encountered as well, and thoroughly investigated.

The issue seems to stem from the fact that 1st generation Airpods, when their microphone is enabled, downgrade their sample rate from 48khz to 16khz.

A temporary work-around I've found is to set BlackHole not as the second output device in the MOD, but as the first. However...that does not work on all computers, and this can sometimes (around once every 10 times) lead to BlackHole totally losing the sound after 2-3 minutes.

Wouldn't the solution be to implement 16khz input for BlackHole ?

Here are two attached screen-shots to show my point : 

[
![Screenshot 2021-01-08 at 14 51 07](https://user-images.githubusercontent.com/27212276/104023016-574af400-51c1-11eb-8e99-8fafd3a14995.png)
![Screenshot 2021-01-08 at 14 51 39](https://user-images.githubusercontent.com/27212276/104023020-57e38a80-51c1-11eb-9ec8-bf155c1da01a.png)

](url)

**Comment by devinroth** [comment]
Oh yes. 16Hz sounds like a possible solution. I’ll test it out once I can. But you said it only happens on first gen?

Devin

**Comment by Lazare-42** [comment]
I don't have second generation AirPods so I can assert this, but it seems only first generation AirPods change their sample rate when their microphone is activated.

I've tried meddling with the C Code of BlackHole to create a 16Khz input, to no avail, so I'll be looking forward to any solution you might bring up!

**Comment by devinroth** [comment]
The issue I have with using 16kHz audio is that the quality will be noticeably degraded. 

I'm using the AirPods Pro and don't seem to have an issue. How exactly is everything setup? 

Another possible solution is to not use a multi-output at all. Instead you can use something like Audacity to route the audio from BlackHole to your headphones. Use BlackHole as the system output and input into QuickTime.

**Comment by devinroth** [comment]
This is the same issue as #146 so I'm going to close it. Let's continue the conversation over there. No need for two.
