### ISSUE TITLE
Within a couple of minites, the sound goes away

### ISSUE THREAD

**Issue by Sean-Kevin** [ExistentialAudio/BlackHole#197]
Hello. 
First of all, thanks for your great work!

Here is my situation!

iMac A : MacOS 10.15.4 Catalina.
MacBook Pro B: MacOS 10.15.2 Catalina.

I built a debug version of BlackHole, signed with no team ,  changed the numbers_of_channels to 2, on iMac A. Which works great!
Then I copy the Driver built from iMac A to a macbook pro B, using a self-built app to try to collect audio data from MacBook Pro B and send the data to iMac A , using the iMac A default output device to play the audio. 
I play a mv with QuickTime Player on MacBook Pro B. Everything goes well at the start of the app launched. After a few minites , the sound suddenlly goes away.
I have checked the coreaudiod on MacBook Pro B, it worked when the sound goes away.
Any clues of this situation?

**Comment by devinroth** [comment]
What errors do you get in Console?

**Comment by devinroth** [comment]
Also are you using an aggregate or multi output?

**Comment by Sean-Kevin** [comment]
No. Not using any aggregate or multi output. Just connect built-in input and BlackHole as output.
As I can see from the log in console. Nothing seems useful.
I checked systemlog (filtered log with keyword coreaudiod).
 Seems like when the sound goes away, some info messages like "powerd Process coreaudiod.963 Released PreventUserIdelSystemSleep "com.apple.audio.BlankHole_UID.context.preventuseridlesleep ..." output to log.

**Comment by devinroth** [comment]
Hmmmm. 

Could you show me an example?

**Comment by Sean-Kevin** [comment]
I will check my app again. Tell your more  info later.

**Comment by Sean-Kevin** [comment]
Hello, after a lot of check and research. I found out that when my app copy the audio data from the I/O cycle which is through from blackhole to built-in output, the coreaudiod always overload , has to "skip cycle due to overload" which comes from system log.  And the coreaudiod takes a lot of CPU , which on iMac about 12%, MacBook Pro about 27%. Does this data be normal? Cause my app crashed due to "com.apple.audio.IOThread.Client" when "com.apple.CoreAudio" calling "HALC_ProxyIOContext".

**Comment by devinroth** [comment]
How much cpu does the coreaudiod take when using something like Logic Pro X? 

On my 2015 MacBook Pro it’s about 6% with a buffer size of 256 samples 44.1k. 3.5% at 1024 and 21.7% at 32. Try playing around with different settings to get the results you want.

You can also adjust the latency in BlackHole. Also give 0.2.7 a try. It may help with performance. If you do please report back.

**Comment by Sean-Kevin** [comment]
I don't have Logic Pro X. 
As far as I can see,  seems like I put too much I/O work in both captruing and sending thread, the I/O work blocked the thread?
By the way, I changed blackhole.driver into 2 channels. But the audio data which I captured from the blackhole as input audio device comes with noise data, like "zizizi..." , sounds like electricity. 
I checked the MIDI , all other devices use integer to calculate samples. but blachhole uses float. The mac os default output an input devices also use integer. Could I change blachhole from 32 float into 32 integer? and how?

**Comment by devinroth** [comment]
It doesn’t have to be Logic. I just used it as an example. Garage Band is free. You can use that.

If you I/O thread doesn’t return in time you’ll get that error.

Interesting about the 2 channel version. I haven’t encountered that myself. 

Yes BlackHole uses Float32 simply because that’s what HAL uses. Everything is presented in Float32 regardless of the format displayed in AudioMidi setup. Even if I added to option for int16 or int24 HAL converts that into Float32. So the conversion happens either on the application end or on the HAL end. For simplicity I decided just to leave it as Float32. Maybe it wouldn’t be convenient to have “virtual” options but there will most likely be a performance hit. 

Also in most DAWs all the math is in Float32 or even Float64. With the exception of saving space for storing audio files, it doesn’t make much sense to be using anything but floats for audio. If you are interested in the performance difference between int and float here is an interesting thread. https://stackoverflow.com/questions/2550281/floating-point-vs-integer-calculations-on-modern-hardware <https://stackoverflow.com/questions/2550281/floating-point-vs-integer-calculations-on-modern-hardware>

In terms of resolution Float32 = Int24 but with some added benefits such as no clipping. 

To answer your question, yes you can change it to support Integer with a virtual format but I don’t think it’s worth it.

**Comment by devinroth** [comment]
Closing. Reopen if it's still an issue with 0.2.8.
