### ISSUE TITLE
Input mirrored on output

### ISSUE THREAD

**Issue by MusicVI** [ExistentialAudio/BlackHole#200]
Hey 

When receive audio on input 2 on Blackhole a copy of the audio input seems to be sent out on output 1 on Blackhole. Is this something I can change?

**Comment by devinroth** [comment]
BlackHole doesn’t map inputs to outputs. Just outputs to inputs. I suspect you have it setup that way somehow. How do you have it setup?

**Comment by yuriteixeira** [comment]
I just tried to use the new version and had the same problems. My setup is:

Code change to enabled the second driver:
- Change `kDevice2_IsHidden` to `false`, then compiled, copied the build artefact and restarted coreaudio. Both virtual interfaces appeared in Audio MIDI Setup.

Sound preferences:
- Output device: **BlackHole 2ch 2** (to capture what is playing in youtube, spotify, etc)

Audio MIDI Setup:
- 1 Aggregate input (MIX IN) assigned to **BlackHole 2ch 2** & the Macbook mic
- 1 Multi-output (MIX OUT) assigned to _BlackHole 2ch_ & the Macbook's connected headset

Garage band:
- Audio IN: uses **MIX IN**
- Audio OUT: uses **MIX OUT**

Video conference (Google Meet): 
- IN: uses _BlackHole 2ch_
- OUT: Macbook's connected headset

Current Result: 
- Sorta unpredictable: sometimes, only what is sent to _BlackHole 2ch_ is captured, but nothing from the mic. Sometimes it gets both, but with a noise that is much louder than the sound. 

Expected Result: 
- The one I got from my fork from your repo (back in the days it was version `0.3.x` at that time, I believe), where I build 2 separate driver artefacts instead of one: https://github.com/yuriteixeira/BlackHoleWithAux/commit/9df65a6f9dddbf40771263832c8e9662a5ff38d4

After hitting my head the whole afternoon by trying to figure out why this setup wasn't working (since it worked before with my version), I've compiled mine and tried in my new Macbook and it worked.
