### ISSUE TITLE
Inconsistency in the documentation for Aggregate Device

### ISSUE THREAD

**Issue by leafac** [ExistentialAudio/BlackHole#219]
https://github.com/ExistentialAudio/BlackHole/wiki/Aggregate-Device:

<img width="870" alt="Screen Shot 2020-10-25 at 21 20 41" src="https://user-images.githubusercontent.com/586813/97119531-c52a6800-1708-11eb-8c81-253af903855a.png">

Is the text or the image right?

Also, out of curiosity, what issues with macOS does this solve? I want to check if I have such issues and if the solution is working.

Thanks for this great project!

**Comment by devinroth** [comment]
The issue is that multi-outputs / aggregates don’t work if the primary device has more than 2 channels. Making sure that built-in output / input the first on the list solves the problem. It may or may not be a problem with aggregates but it definitely is with multi-outputs. I’ve submitted a bug report to Apple regarding this so I hope it is fixed soon. 

Hope that clears it up. I definitely have a better understanding of the problem now so maybe the documentation should reflect that.

**Comment by leafac** [comment]
Oh, so **both** the text **and** the image are correct!

Thanks for the explanation.
