### ISSUE TITLE
Blackhole latency and glitching

### ISSUE THREAD

**Issue by tombburnell** [ExistentialAudio/BlackHole#30]
Hi, Cool that you have built this. well done!

I've been trying it out, feeding 8 channels of Traktor DJ output (4 stereo pairs) into blackhole and then picking them up Ableton to play alongside prerecorded tracks from Ableton.  I'm finding the Trakor tracks via Blackhole have a greater latency doing this than using the equivalent loopback feature on my RME soundcard. I don't always have my sound card available so it would be great to have the option to use this. Any idea why this is?

I also get quite bad glitching after a while. Is this to do with the clocking issue raised in  #27? ie the "blackhole" input interface is not synced to the "internal audio" output interface of my macbook in Ableton?

Best, Tom

**Comment by devinroth** [comment]
Yeah it’s because of clocking. In fact your previous comment about latency is also a result of clocking. Although I might have a few other thoughts about it. Assuming you buffers are set to 256. You get 256 latency from Traktor into Ableton and 256 from Ableton to your audio output for a total of 512. Now if you are inputting from Traktor to RME you have a 256. RME will then send audio directly to your speakers which will bypass any additional buffer from Ableton. 

You could as a comparison try setting up a multi-output device with your speakers and blackhole. Output Traktor to that and you’ll remove Ableton from the chain. If you put Ableton between Traktor and your speakers you are adding additional latency.

AS for clocking, After time the clocks will drift out of sync and cause the glitches you describe. Having the ability to sync clocks is one of my top priorities. It just a matter of time before I get to it. 

Have you tried using an aggregate device? It might solve the clocking issue with drift correction. In fact the multi-output device might solve all your problems. Play around with it and let me know.

**Comment by tombburnell** [comment]
Hi Devin,
Thanks for getting back. 

In my latency comparison, the routing is more or less the same:

- Traktor -> RME  -> RME-loopback -> RME -> Ableton   -> RME

- Traktor -> Blackhole -> Loopback ->Blackhole -> Ableton -> Xone K2 soundcard

When comparing these, both have some latency, but RME seems to have less latency and is more stable.

I could simply bypass Ableton eg:
Traktor->RME
Ableton->RME
  or 
Traktor -> macbook headphones
Ableton -> macbook headphones

I don't think I really need the aggregate device for this. But then I don't have the possibility to record the Traktor clips into Ableton or apply Ableton FX (which is key part of my objective).

**Comment by devinroth** [comment]
Test it with a multi output as I suggested and report back. 

And what are your buffer sizes?

**Comment by devinroth** [comment]
I’m just going to close the issue since it’s all related to clocking. Feel free to comment if you try out some other settings.  I’m curious of the results.

**Comment by tombburnell** [comment]
Hey, I think I've figured out what's causing my issue - might be of interest to you and maybe you can advise on it.

 Basically I've worked out that the glitching arises when I have Traktor Full screen and Ableton hidden.

Most of my testing i've done away from my studio in my lunch hour at work where I just have the single monitor. At home, when I've been using my soundcard, Ive got a 2nd monitor and have Ableton full screen at the same time.

So it seems the problem is due to either Traktor doing something while it's full screen or Ableton not liking being hidden. 

I've tried to use 'renice' to keep Ableton high priority but that hasn't helped. 

After an hour of testing using blackhole as the routing between Traktor->Ableton and my Xone K2 as soundcard it's been pretty stable. I think there were a few glitches but need to test a bit longer - I might need to check buffer sizes but it's looking quite good so long as I maintain both open windows.

Anyway, it seems the answer in my case is not about the the choice of loopback software but about making sure both apps are visible. I actually do have a small 2nd screen I can use but curious if you have any alternative suggestions that might also work. 

Best, Tom

**Comment by devinroth** [comment]
Interesting. Seems like such a strange bug. 

Not sure what the solution is for that. Thanks for the update.
