### ISSUE TITLE
Desktop Audio Not Being Captured Big Sur

### ISSUE THREAD

**Issue by CallmeTorre** [ExistentialAudio/BlackHole#335]
I update my OS to Big Sur and BlackHole stop working. I have the exact setup as the tutorial and is not reproducing any video or audio. I follow [these steps](https://github.com/ExistentialAudio/BlackHole#why-is-nothing-playing-through-blackhole) and is not working. Any idea?

**Comment by devinroth** [comment]
Try reinstalling.

Devin

**Comment by quenbyako** [comment]
Got same problem too.

Macos big sur, m1 silicon, installed blackhole-16ch via brew (`brew install blackhole-16ch`)

after i created multi-output device, change desktop outuput to it, EVERY (literally every, not kidding) video player from firefox, safari, even from ps remote play **just stuck** (lol, this is first time when i see bug like this one).

I think, that all of them wait until blackhole be ready to read data from them, but not sure about that. @devinroth any idea what happened?

**Comment by quenbyako** [comment]
No way, after i installed 2 channel version, it doesn't stuck anymore 😂😂😂😂😂😂

I working with alsa only (linux subsystem), and currently i'm not sure how exactly sound system works in macos.

**Maybe** (this is only my idea) all apps which using audio try to send 2ch events and kernel want to force push it to 16 channel device and, of course, fails. If you need any feedback to this issue, you can write me on telegram or email, i'll try to provide more info and kernel logs, if them necessary

**Comment by devinroth** [comment]
It’s a multi output bug. It’s listed in the faq and every documentation I have.

Devin

**Comment by quenbyako** [comment]
@devinroth is it able to fix somehow by hands, or apple as always just ignoring this bug? cuz it's realy pain in the ass while i trying to figure out how to deal with it

**Comment by devinroth** [comment]
Waiting on Apple.

Devin

**Comment by devinroth** [comment]
The best way to deal with it is put the built-in output on the top of the list and just mute it.

Devin

**Comment by quenbyako** [comment]
@devinroth even with top listed built-in output audio is stuck.

Works on built-in speakers + jack output, works by single device. but even when blackhole device is end of the list, it's not working for me 😭 don't know why, but i hope that this bug can be fixed somehow

**Comment by zamboknee** [comment]
Same issue. M1 mac mini, Big Sur (11.2.2).
How do you 'mute' the 'built in output' ?@devinroth?
Thank you.

**Comment by nstefi** [comment]
I have the same issue on MacBook Pro with M1 chip, Big Sur 11.2.3.
When I create a multi-output device that includes the MacBook Pro Speakers and BlackHole 16inch, if I try to play a video on YouTube, it freezes.
Devin you said "The best way to deal with it is put the built-in output on the top of the list and just mute it".
I don't really understand what you meant here. I have checked the built-in output (MacBook Pro Speakers) first in the multi-output device, so that's on the top, but what you mean to mute it? You mean uncheck in the Use column, then it would not be added, and there would be no sound.
So this is an Apple issue? I still have my laptop in warranty, and I can open a case, but if all the other features are working there is no obvious issue that I could show them and complain about.
Is that multi output bug listed on some Apple site that we can track?
Thanks.
