### ISSUE TITLE
Latency, Tempo, and Audio drops

### ISSUE THREAD

**Issue by aiotea** [ExistentialAudio/BlackHole#444]
Hi there! I'm using Blackhole 16ch on my M1, and having various issues.  I'm routing audio from DJPro AI to Ableton. 

First, audio had a drifting tempo... very noticeable, so I made an aggregate device, added Blackhole 16ch and toggled on drift correction. Now the audio cuts in/out of playing/silence every few seconds. 

I've tried with the Blackhole 2ch and am having the same issue.  Here's a video showing what's happening: https://youtu.be/4n5FBtohz-M

Note: Rob DJ is the name of my aggregate audio device you'll see in the video.  

Thank you for any help diagnosing this!

**Comment by aiotea** [comment]
Any ideas for how I can troubleshoot?

**Comment by designerfuzzi** [comment]
Same here.. no matter what amount of channels i compile and use then i get audio drops and cracles each 3 - 5 minutes that disappear after about 5 seconds and come back again..
Tried to change settings to system Samplerate (MacBookPro 2009) 44100.0f but it falls back to 48.000 .. guessing there is a buffer issue in code. Drift correction is not available when using with Ableton, because then you route directly..

my Setup routing is 
> Ableton Master Out 
>> Blackhole 16ch on 1&2
>>> Into my own Audio App catching Blackhole Device via CoreAudio
>>> From there Output to External Audio Device..
It works fine, just the crackles now and then..

As i can record the Blackhole Output in my App i can even record the crackles.. meaning they appear between
 Ableton and Blackhole and HAL system not down the chain..

**Comment by devinroth** [comment]
Hey Frank. Sounds like a completely different issue.

No idea what’s happening here Rob. You can test if it’s an issue with BlackHole by using it without an aggregate. Obviously you won’t be able to hear but if you can record with BlackHole2ch without issue the problem is the aggregate. Unfortunately some applications do a terrible job of supporting aggregate devices.

Test that out and report back.

Devin

**Comment by designerfuzzi** [comment]
aggregate devices are not that much different than any other source/destination.. they have their dedicated API that needs to be used [in example some of those in this gist](https://gist.github.com/rlxone/584467a63ac0ddf4d62fe1a983b42d0e).
As developer you can not make a terrible job with that otherwise it just doesnt work at all.

maybe a freaky question.. is Blackhole supposed to work only in combination with another source/destination as aggregated device? Because in my question there is no aggregated device involved. just plain routing..

**Comment by devinroth** [comment]
Frank just open a different issue because yours is not related.

Devin
