### ISSUE TITLE
Forwarding delay/latency information for audio video sync?

### ISSUE THREAD

**Issue by zplizzi** [ExistentialAudio/BlackHole#533]
I notice that when I have the folloiwng setup (OSX):

video player (ie netflix in chrome) -> blackhole -> logic pro x (running eq/room correction plugins) -> bluetooth speakers

the video and audio are out of sync (the audio lags significantly behind the video, more than the latency of my audio drivers). However, when I directly play netflix to the bluetooth speakers, there's no syncing issue. I understand that bluetooth devices have a lot of latency, and report this latency so that the computer somehow can bring the devices in sync - I see AVDTP as one potential protocol for this. So I imagine what's happening is that either Logic or blackhole is dropping / blocking this latency information from being transferred or handled properly?

I'm just wondering if there's anything that can be done to solve this situation (short of manually adjusting latencies somehow). Thanks! Love the tool :)

**Comment by devinroth** [comment]
Let's see. I'm going to guess some numbers but hopefully you'll understand what's going on. Netflix -> BlackHole 512 frame buffer 12ms but Netflix knows this so it delays the video to match. BlackHole -> Logic at 1024 buffer 23ms delay that Netflix doesn't know about. Logic input monitoring is going to have an extra delay to buffer between the input and output devices of an unknown amount. Let's say another 12ms. Then another 23ms to output to your Bluetooth speaker driver. But that's just to the driver so there's another 92ms delay sending the audio to the speakers before you actually hear anything. 

When you go from Netflix to your speakers Netflix knows how long audio will take to get to your speakers, but when you add something else in-between Netflix no longer has that information. In my example that's at around 150ms. Nothing is being dropped or blocked and everything is working as it should. In order to have that exact same setup and get the video to sync you'll have to "lie" to Netflix about the delay saying it's 150ms. The trick would be to set a higher safety offset but internally compensate by not actually using that safety offset. 

If you enjoy getting your hands dirty and building a custom version, have fun, but it's not something that I currently plan on implementing.

**Comment by zplizzi** [comment]
Thanks for the detailed reply!

> When you go from Netflix to your speakers Netflix knows how long audio will take to get to your speakers, but when you add something else in-between Netflix no longer has that information.

I guess my question was: would it be possible for the "something in between" to query the output device (bluetooth speakers) for their latency, and then respond when Netflix asks for the latency with that latency number. Thus "passing through" the latency information. So basically Netflix asks blackhole how much latency it has, and blackhole asks logic, and logic asks the bluetooth speakers, and then they each pass that number back up (maybe adding their own additional latency) to Netflix.

Obviously Logic would have to support this too for it to be useful, and I'm guessing they do not.

**Comment by devinroth** [comment]
Not really possible unless you manually set it as described earlier.

Devin
