### ISSUE TITLE
Installer Modifies Permissions of Unrelated Directories/Drivers

### ISSUE THREAD

**Issue by TurtleWilly** [ExistentialAudio/BlackHole#818]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 10.10 Yosemite

### BlackHole Build(s) Affected

- [X] 2 channel
- [X] 16 channel
- [X] 64 channel
- [ ] other/custom build

### Describe the bug

The installer archives (2ch, 16ch, 64ch) bothin the pre- and the post-install steps do the following:

```bash
sudo chown -R root:wheel /Library/Audio/Plug-Ins/HAL
```

This is to broad and other drivers with (perhaps wanted/needed) other permission setup in the `/Library/Audio/Plug-Ins/HAL` directory get modified too.

It only should modify/adjust what it just had installed, e.g:

```bash
sudo chown -R root:wheel /Library/Audio/Plug-Ins/HAL/BlackHole2ch.driver
```

### Reproduction Steps

Installer changes permissions of non-BlackHole drivers in /Library/Audio/Plug-Ins/HAL

### Expected Behavior

Installer doesn't modify random directories in /Library/Audio/Plug-Ins/HAL

**Comment by devinroth** [comment]
I get what you are saying but every thing including the HAL folder needs to have those permissions in order to run properly with core audio.

The reason I did this was I was getting issues where the HAL folder for whatever reason was not set to this and subsequently BlackHole would not get loaded by CoreAudio. So this was added to fix that.

So unless you can actually show me that it causes unintended consequences or any documentation contrary to my knowledge I’m not inclined to change it.

More strict would be to set the permission for the HAL folder and BlackHole and forget about everything else. But it absolutely is needed for the HAL folder.

**Comment by devinroth** [comment]
Who is this person? If not yourself, why were you tasked with helping them? Something about your story does not add up.

It’s little absurd that you think I would do those other things. I think you’re just saying it in jest but it’s rather offensive.

If something broke it was more likely due to sudo kill rather than the permission thing. So unless the thing that broke was another audio driver for which the permissions were changed, there is no way that the permissions caused any issue. On the other hand, some apps don’t handle kill all for system processes correctly and as a result it can cause problems. Apple recommends restarting the computer after installing a driver.

I think you’re assuming a bunch of incorrect things.

That being said, I like your solution and will make the change but I strongly believe it has absolutely nothing to do with the issue you mentioned.
