### ISSUE TITLE
SuperCollider -> Hangouts

### ISSUE THREAD

**Issue by KonVas** [ExistentialAudio/BlackHole#82]
System: MacOS(10.15.3 Catalina).
I am trying to use Hangouts for testing reasons, routing SuperCollider(fig1) to Hangouts(fig2) for example. Although I can see SC used the out that I am selecting succesfully the sound is not ported in the hangouts when I am selecting the hangouts:mic option set to BlackHole, similarly I tried everything I read on this git's issues including using aggregate and or multiout devices configs but no success. Settings attached (fig3).
![Image](https://user-images.githubusercontent.com/6897992/77665993-73163e00-6f91-11ea-9c5e-76a152346456.png)
Fig 1.

![Image](https://user-images.githubusercontent.com/6897992/77665862-44986300-6f91-11ea-8d6b-e029289bf239.png)
Fig 2.

![Image](https://user-images.githubusercontent.com/6897992/77666596-33038b00-6f92-11ea-9e4c-4096708c53d5.png)
Fig 3

**Comment by devinroth** [comment]
No idea why it isn’t working off the top of my head. I’ll download SuperCollider and try it out. 

Devin

**Comment by KonVas** [comment]
> No idea why it isn’t working off the top of my head. I’ll download SuperCollider and try it out. Devin
> […](#)
> On Mar 26, 2020, at 8:42 AM, Konstantinos Vasilakos ***@***.***> wrote: ﻿ I am trying to use Hangouts for testing reasons, routing SuperCollider(fig1) to Hangouts(fig2) for example. Although I can see SC used the out that I am selecting succesfully the sound is not ported in the hangouts when I am selecting the hangouts:mic option set to BlackHole, similarly I tried everything I read on this git's issues including using aggregate and or multiout devices configs but no success. Fig 1. Fig 2. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by berkeleybernie** [comment]
I'm new to this and was trying to set this up using Reaper DAW as a mixer to route output to OBS using an aggregate device of Blackmagic/Audio Interface in Reaper. I was getting no audio in OBS. Turned out that one has to configure the routing in Reaper so that the aggregate device doesn't output back to the input device (in my case, I was using a Zoom H5). Once I used the routing matrix (not in the audio preferences; an additional step) in Reaper to include Blackmagic channels, OBS was able to see the Reapers audio output.

Maybe some kind of routing necessary in SuperCollider as well?

**Comment by KonVas** [comment]
> Maybe some kind of routing necessary in SuperCollider as well?
If I am getting it right, you want SC to use BlackHole as output, assuming yes: evaluate this block as one piece of code:

(
// s = Server.local;
s.options.inDevice = "Built-in Microph";
s.options.outDevice = "BlackHole 16ch";
s.reboot; 
// turns to BlackHole only after rebooting the server.
)
