### ISSUE TITLE
using blackhole to record system audio: recods only MONO

### ISSUE THREAD

**Issue by barturas** [ExistentialAudio/BlackHole#86]
I'm trying to perform quicktime screen record with system sound but quicktime only records in mono when blackhole selected as an input. 
QT does record audio in stereo when my 2ch mic is selected as an input.

**Comment by devinroth** [comment]
Interesting. I’ll look into it.

**Comment by barturas** [comment]
let me know if you need any additional elaborations :)

**Comment by devinroth** [comment]
I just tested and I definitely don't get mono. In fact, I get surround since BlackHole has 16 channels.

What exactly are you recording and how?

**Comment by GitHubDuck** [comment]
Just looking into a similar thing and I get a 15.1 surround recording due to QuickTime seeing the BlackHole input as 16 channels. I'd like to get a 2 channel stereo recording, so does that mean I'd need to change the number of channels of BlackHole to 2 to make this work?

**Comment by GitHubDuck** [comment]
![Screen Shot 2020-04-01 at 10 17 09 pm](https://user-images.githubusercontent.com/62994735/78131302-95fb9300-7466-11ea-85e4-efa0851f133b.png)

**Comment by devinroth** [comment]
Yes I think the solution is using a 2ch version. I'm working on adding one to my website. Hopefully it will be up by the end of the week.

**Comment by barturas** [comment]
hey Devin, I wanted to perform screen record with system sound. I installed Blackhole, in Audio MIDI Setup I created Aggregated device (use built-in output + blackhole) and created Multi Output device (Built-in output + Blackhole). Then Iin QT I selected to use my aggregated device to use as a sound source. It records but it is MONO. I did same with Sunflower and sound is recording in STEREO.
Another thing worth mentioning is that I can see active control of Master and channel levels (see picture) but in Blackhole those were inactive.
![Screenshot 2020-04-01 at 17 43 12](https://user-images.githubusercontent.com/34832768/78150831-7d788200-7440-11ea-80a1-92bbcea0d21f.jpg)

**Comment by devinroth** [comment]
The issue may be with the aggregate device (they are known to be buggy). But probably also because you’re using Soundflower 2ch? I bet the issue will be solved with BlackHole 2ch. Under the hood I am able to create virtual audio formats which may also solve the problem but I haven’t had the time to look into that yet.

As for the for the levels of individual channels, I have decided to leave them inactive in BlackHole largely for performance reasons. The master volume still works but for most cases using the volume for individual channels adds significant overhead with minimal benefit. It’s better to set the volume in the app that uses BlackHole instead.

**Comment by pablogeek** [comment]
I'm also having this issue. I succeed trying to record the system output and microphone at the same time but the produced video is only Mono.

Here is my config:

I create the multioutput device to be able to also hear what I'm recording:

<img width="618" alt="Screenshot 2020-04-03 at 14 41 31" src="https://user-images.githubusercontent.com/1773546/78361770-3792f980-75b9-11ea-9dd4-0e5c259fefb2.png">

I create the aggregate device to be able to add this as a input of my recording session:

<img width="619" alt="Screenshot 2020-04-03 at 14 39 45" src="https://user-images.githubusercontent.com/1773546/78361903-73c65a00-75b9-11ea-85cb-69ef460c7079.png">


With this config I'm able to record system and microphone audio and also hear the system audio while I'm recording it. But the final video is MONO.

will that work with Blackhole 2ch?

**Comment by devinroth** [comment]
2ch should solve the problem. There are build instructions in the wiki. Or wait until I release a 2 channel version.

**Comment by pablogeek** [comment]
Hey @devinroth thank you for your quick reply! I really appreciate it!

I was able to compile the driver for 2 channel. 

Now the blackhole driver looks like this which I guess is fine. But it is still happening, I can only hear the system audio from my left speaker. Interestingly my voice coming from the mic is playing in both speakers. So it's like the mic in the aggregate device produces audio dual channel and blackhole driver only 1

<img width="611" alt="Screenshot 2020-04-03 at 18 58 55" src="https://user-images.githubusercontent.com/1773546/78386056-2c51c500-75dd-11ea-9b02-3b0febe91908.png">

**Comment by devinroth** [comment]
Are you routing your mic to blackhole channel 1-2 or just to one?

Devin

**Comment by pablogeek** [comment]
I guess this says both right?

<img width="627" alt="Screenshot 2020-04-03 at 19 09 49" src="https://user-images.githubusercontent.com/1773546/78386891-b2224000-75de-11ea-9b89-91b111eaa9a4.png">

**Comment by devinroth** [comment]
Okay i get what you’re doing wrong. You are only recording your mic and nothing else. QT is recording one channel of your mic and one channel of Blackhole with nothing going through it. Use a daw to mix the mic and black hole. 

Devin

**Comment by pablogeek** [comment]
Thanks for your reply. Probably is what you are saying. I did a test adding only the Blackhole in the aggregate input device instead of adding Blackhole and microphone. It worked.

Basically if Blackhole is alone as the only source, it plays in both speakers. Kind of weird isnt?

<img width="627" alt="Screenshot 2020-04-03 at 20 06 58" src="https://user-images.githubusercontent.com/1773546/78391453-af2b4d80-75e6-11ea-989b-1b893d6fd341.png">

**Comment by devinroth** [comment]
Glad you got it figured out.

**Comment by omc2016** [comment]
Updated NUMBER_OF_CHANNELS to 2 in BlackHole.h and I was also able to make stereo recording work on Quicktime Player and the macOS screenshot utility.  Thank you.

**Comment by herrernst** [comment]
I'd very much like to have a 2 channel version too, because it would simplify some tasks (like recording with Quicktime). Thanks!

**Comment by cellulosa** [comment]
Hi there, I'm using the 2ch version but still get audio mono'ed. If I record both the internal sound and the microphone, each get assigned to either left or right. Is there a way to solve this?

**Comment by devinroth** [comment]
That’s not a BlackHole issue. You’re just setting it up wrong.

Devin

**Comment by cellulosa** [comment]
> That’s not a BlackHole issue. You’re just setting it up wrong. Devin

I see. I followed the wiki to setup the aggregate device and multi-output device but I can't see anywhere in the `Audio MIDI Setup` app options to direct channels per device?

**Comment by devinroth** [comment]
Correct. That is from the audio app that is using BlackHole.

Devin

**Comment by quadrup** [comment]
<img width="796" alt="Bildschirmfoto 2022-06-09 um 16 48 52" src="https://user-images.githubusercontent.com/107199777/172877398-da4d7afc-e72d-47f5-a182-9c49e84a235f.png">
<img width="431" alt="Bildschirmfoto 2022-06-09 um 16 52 32" src="https://user-images.githubusercontent.com/107199777/172877418-abda3d0b-cefe-4552-bc70-d9b4dbf6887b.png">

I found out, that once I drag and drop my microphone to the left of the BlackHole device-symbol in Audio-MIDI-Setup, then the mono-audio is fixed and I get stereo-recordings. I have no clue why and what the drag and drop is for. I am just glad that it works. Hope it helps anyone.

**Comment by quadrup** [comment]
Well now I found out, that the drag and drop is for changing the order of the devices, and by dragging the built-in microphone to the very left I put it as the top device just as the wiki recommends in step 4 of the wiki-article about "aggregate device" in the according screenshot.

**Comment by nleco** [comment]
> 

This helped me out! Thank you. It solved my "hearing my external apple earbuds mic recording on one side"

**Comment by neilbaldwin** [comment]
Is there a definitive guide to solving this because I'm having the same issue trying to QT screen record audio from Ableton Live.

The only way I could get it working was to create a multi-output audio device that combines Blackhole 2 Ch and 2 channels of my iConnectivity audio interface. Then in Live the main output is to this multi-output device. I have to do this so that I can hear the audio from Ableton.

Then I have to create an aggregate audio device with the same two devices (Blackhole and iConnectivity) and in QT set the audio to record from this aggregate.

This then lets me screen-record videos in QT with audio but the audio is always mono. Thought I was losing it and then discovered this thread with others having the same issue.

I'm aware this has been closed but can't find information on why it's happening and how to solve it.

**Comment by devinroth** [comment]
Your issue is an aggregate does not mix audio together. I'm building an app to solve that. Try the alpha out from discord. https://discord.com/channels/775472045865173023/1047774289480400986/1113952236733730907

**Comment by neilbaldwin** [comment]
Cheers Devin. Good to hear and I look forward to trying that out 👍

**Comment by neilbaldwin** [comment]
Update: spent the morning digging into this problem. Seems the mono thing is a Quicktime issue. I also tried the app 'Kap' but I suspect that is built on QT as it exhibits the same summing quirk. A bit of searching around and a lot of other people seem to have run into the same mono issue.

Instead I tried OBS and was able to record audio from Live using an Multi-Output device for monitoring purposes (Blackhole + my iConnectivity interface) and in OBS just set Audio Input Capture to Blackhole and it works perfectly.

👍
